#####################
### LOOK AND FEEL ###
#####################

splash = false
ipc = on

# NOTA: wallpapers de monitores externos se aplican dinámicamente vía
# setup-monitors.sh (porque sus puertos cambian). Acá solo el built-in.

wallpaper {
    monitor = eDP-1
    path = ~/Pictures/Wallpapers/great-wave-of-kanagawa-gruvbox.png
}

wallpaper {
    monitor = HDMI-A-1
    path = ~/Pictures/Wallpapers/wallpaperbetter.jpg
}
